# Generated by Django 6.0.5 on 2026-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('fathom', 'Fathom'), ('ai', 'AI')], default='fathom', max_length=20),
        ),
    ]
