# Generated by Django 6.0.5 on 2026-05-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_fathomconfig_meeting_task_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
