# Generated by Django 6.0.5 on 2026-05-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fathomusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='share_url',
            field=models.URLField(blank=True),
        ),
    ]
