# Generated by Django 6.0.5 on 2026-06-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_scheduledmeeting_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True, help_text='Base64 encoded image data', null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='New', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto-capture', 'Auto-captured')], default='manual', max_length=20)),
                ('source_ref', models.CharField(blank=True, help_text='Reference to the source meeting/comment', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlog_items', to='api.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
