# Generated by Django 6.0.5 on 2026-06-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_backlogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='created_task',
            field=models.ForeignKey(blank=True, help_text='Task auto-created from this backlog item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlog_source', to='api.task'),
        ),
    ]
