# Generated by Django 6.0.5 on 2026-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_backlogitem_created_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='fathomconfig',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle for all email notifications (task assignments, meeting invites, etc.)'),
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Future Consideration', 'Future Consideration')], default='New', max_length=20),
        ),
    ]
