# Generated by Django 6.0.5 on 2026-06-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_fathomconfig_email_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='meeting_date',
            field=models.DateTimeField(blank=True, help_text='Date/time of the source meeting', null=True),
        ),
    ]
