# Generated by Django 6.0.5 on 2026-06-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_backlogitem_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='release_week',
            field=models.CharField(blank=True, help_text='Target release week e.g. W25, W26', max_length=4),
        ),
    ]
