# Generated by Django 6.0.5 on 2026-06-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_backlogitem_release_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, help_text='When backlog_scan last processed this meeting', null=True),
        ),
        migrations.CreateModel(
            name='DismissedSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(help_text='MD5 hash of meeting_id + title + proposed_enhancement', max_length=64)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_suggestions', to='api.meeting')),
            ],
            options={
                'unique_together': {('meeting', 'content_hash')},
            },
        ),
    ]
