# Generated by Django 6.0.5 on 2026-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_meeting_last_scanned_at_dismissedsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogitem',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Closed', 'Closed'), ('Future Consideration', 'Future Consideration')], default='New', max_length=20),
        ),
    ]
