# Generated by Django 6.0.5 on 2026-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_revert_single_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='eta',
            field=models.DateField(blank=True, help_text='Estimated completion date', null=True),
        ),
    ]
