# Generated by Django 6.0.5 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_backlog_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fathomconfig',
            name='api_keys',
            field=models.JSONField(blank=True, default=list, help_text='All Fathom account API keys. Sync searches every account, so anyone who stays in the meeting gets picked up.'),
        ),
        migrations.AlterField(
            model_name='fathomconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
