# Generated by Django 6.0.5 on 2026-08-05

from django.db import migrations


def convert_api_keys_to_entries(apps, schema_editor):
    """Normalize existing plain-string api_keys to {key, added_by, added_at} dicts."""
    FathomConfig = apps.get_model('api', 'FathomConfig')
    for config in FathomConfig.objects.all():
        raw = config.api_keys or []
        entries = []
        for item in raw:
            if isinstance(item, dict):
                entries.append(item)
            elif isinstance(item, str) and item.strip():
                entries.append({'key': item.strip(), 'added_by': '', 'added_at': ''})
        config.api_keys = entries
        config.save(update_fields=['api_keys'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_fathomconfig_api_keys'),
    ]

    operations = [
        migrations.RunPython(convert_api_keys_to_entries, migrations.RunPython.noop),
    ]
