# Generated by Django 6.0.5 on 2026-08-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_fathomconfig_key_uploaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.BooleanField(default=False, help_text='True = process all meetings; meeting must be null')),
                ('force', models.BooleanField(default=False, help_text='Delete existing auto-generated tasks before regenerating')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('task_count', models.IntegerField(default=0)),
                ('backlog_count', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_failed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_generation_jobs', to='api.meeting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
