# Generated by Django 6.0.5 on 2026-08-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_taskgenerationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FathomWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
                ('webhook_id', models.CharField(blank=True, max_length=100)),
                ('secret', models.CharField(blank=True, help_text='whsec_... used to verify incoming webhook signatures', max_length=500)),
                ('destination_url', models.CharField(max_length=1000)),
                ('triggered_for', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('api_key',), name='unique_fathom_webhook_per_key')],
            },
        ),
    ]
